FROM python:3.10

WORKDIR /app

# Installation les dépendances systeme nécessaires à OpenCV pour lire ou afficher les images
RUN apt-get update && apt-get install -y \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender1 \
    libgl1 \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Création du répertoire dans l'image   # Modèle supérieur à 100 Mo, Github ne l'accepte pas
#RUN mkdir -p /app/artifacts
# Copie du modèle dans l'image
#COPY artifacts/best_model.keras /app/artifacts/best_model.keras

# Dossier pour stocker le modèle téléchargé
RUN mkdir -p /app/artifacts


EXPOSE 8000

CMD ["uvicorn", "app_fastapi:app", "--host", "0.0.0.0", "--port", "8000"]
